---
title: "Benchmark code test"
author: "Sisi"
date: "7/18/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# load the package
library(tictoc)
library(DesignLibrary)
library(dplyr)
source('uihelpers.R')
source('common.R')
source('inspect_helpers.R')
# ---------------------------- functions -----------------------------------
# return args which are not vectors, num cannot be larger than 3 
args_index <- function(name, num, arg_defs){
    # find out all the vector parameters in 
    for (index in 1:length(name)){
        if (arg_defs[arg_defs$names == name[index],]$vector == T){
            name[index] <- NA
        }else{
            next()
        }
    }
    # remove all the NA, get the argname without vector 
    argname_novec <- name[!is.na(name)]
    # all the possible index combinations of args
    args_index <- expand.grid(rep(list(seq(1:length(argname_novec))),num))
    
    if (num > 2){
        # order the dataframe 
        args_index <- args_index[order(args_index[,1], args_index[,2]),]
        # the values in the var1 should be smaller than the values in var2
        # similarly, the values in the var2 should be larger than the value in var3
        args_index <- args_index[args_index[1] < args_index[2] & args_index[2] < args_index[3],]
    }else if (num == 2){
        # remove the combinations with same elements 
        args_index <- args_index[sapply(1:nrow(args_index), function(x){length(unique(unlist(args_index[x,]))) >1}),]
        # order the dataframe 
        args_index <- args_index[order(args_index[,1]),]
        args_index <- args_index[args_index[1] < args_index[2],]
    }else{
        args_indexy <- argname_novec
    }
    
    rownames(args_index) <- NULL
    # args_index is not equal to argname any more! 
    return(list(argname_novec,args_index))
}

# get design, arguments definition, arguments evaluation
diagnose_varying_args <- function(num, id){
    
    design <- get_designs(id)[["design"]]
    arg_defs <- get_designs(id)[["arg_defs"]]
    args_eval <- get_designs(id)[["args_eval"]]
    argname <- names(args_eval)
    index <-  args_index(argname, num,  arg_defs)
    # get the agrname without vector
    agrname_novec <- index[[1]]
    # all possible combinations of arguments
    arg_index <- index[[2]]
    if (num == 1){
        first_arg <- 1
        second_arg <- NULL
        thrid_arg <- NULL
    }else if(num == 2){
        first_arg <- 1
        second_arg <- 1
        thrid_arg <- NULL
    }else{
        first_arg <- 1
        second_arg <- 1
        thrid_arg <- 1
    }

    
    for (i in 1:nrow(arg_index)){
        first_arg <- agrname_novec[arg_index[i,][[1]]]
        if (first_arg  == 'N') {
            n_int <- args_eval[[first_arg]]
            args_eval[[first_arg]] <- seq(n_int,  n_int + 100, 10)
        } else {
            min_int <- arg_defs[arg_defs$names == first_arg,]$inspector_min
            step_int <- arg_defs[arg_defs$names == first_arg,]$inspector_step
            max_int <- min_int + 4*step_int
            args_eval[[first_arg]] <- seq(min_int,  max_int, step_int)
        }
        
        if (!is.null(second_arg) & !is.null(thrid_arg) & !is.null(first_arg)){
            second_arg <- agrname_novec[arg_index[i,][[2]]]
            thrid_arg <- agrname_novec[arg_index[i,][[3]]]
            # vary the second args
            min_int <- arg_defs[arg_defs$names == second_arg,]$inspector_min
            step_int <- arg_defs[arg_defs$names == second_arg,]$inspector_step
            max_int <- min_int + 4*step_int
            args_eval[[second_arg]] <- seq(min_int,  max_int, step_int)
            # vary the thrid args
            min_int <- arg_defs[arg_defs$names == thrid_arg,]$inspector_min
            step_int <- arg_defs[arg_defs$names == thrid_arg,]$inspector_step
            max_int <- min_int + 4*step_int
            args_eval[[thrid_arg]] <- seq(min_int,  max_int, step_int)
            
            tic(paste(first_arg, second_arg, third_arg, id, sep = ","))
            
            all_designs <- eval_bare(expr(expand_design(designer = design, expand = TRUE, !!!args_eval)))
            simdata <- simulate_designs(all_designs, sims = 100)
            diag_info <- get_diagnosands_info(design)$diagnosands_call
            diag_res <- diagnose_designs(simdata, bootstrap_sims = 30)
            
            toc()
            args_eval <- get_designs(id)[["args_eval"]]
        }else if(!is.null(second_arg)){
            second_arg <- agrname_novec[arg_index[i,][[2]]]
            # vary the second args
            min_int <- arg_defs[arg_defs$names == second_arg,]$inspector_min
            step_int <- arg_defs[arg_defs$names == second_arg,]$inspector_step
            max_int <- min_int + 4*step_int
            args_eval[[second_arg]] <- seq(min_int,  max_int, step_int)
            
            tic(paste(first_arg, second_arg, id, sep = ","))
            
            all_designs <- eval_bare(expr(expand_design(designer = design, expand = TRUE, !!!args_eval)))
            simdata <- simulate_designs(all_designs, sims = 100)
            diag_info <- get_diagnosands_info(design)$diagnosands_call
            diag_res <- diagnose_designs(simdata, bootstrap_sims = 30)
            
            toc()
            args_eval <- get_designs(id)[["args_eval"]]
        }else{
            tic(paste(first_arg,id, sep = ","))
            
            all_designs <- eval_bare(expr(expand_design(designer = design, expand = TRUE, !!!args_eval)))
            simdata <- simulate_designs(all_designs, sims = 100)
            diag_info <- get_diagnosands_info(design)$diagnosands_call
            diag_res <- diagnose_designs(simdata, bootstrap_sims = 30)
            
            toc()
            args_eval <- get_designs(id)[["args_eval"]]
        }
    }
}
```

## Running Code Time 
### Slowest simulation of design

Compare the running time of simulations of all the designs, design parameters are initialized with default values. It's easy to see that the slowest is cluster_sampling_designer, and the fastes is randomized_response_designer.

```{r default sim, echo=F, warning=FALSE}
# get all the design names 
cached <- str_replace(grep("designer$", ls(as.environment("package:DesignLibrary")), value = TRUE), "_designer", "")
option <- c()
for (i in 1:length(cached)){
    if (is.null(attr(getFromNamespace(paste(cached[i], sep = "_", "designer"), 'DesignLibrary'), "shiny"))){
        next()
    }else{
        option[i] <- paste(cached[i], sep = "_", "designer")
    }
}
option <- option[complete.cases(option)]

# find the slowest design by simulation 
for (id in option){
    tic(id)
    sim_design <- getFromNamespace(id, 'DesignLibrary')
    simulate_design(sim_design(), sims = 100)
    toc()
}

```

Binary IV design

```{r cars, echo=F, warning=FALSE}
diagnose_varying_args(num = 2, id = option[1])
```

