
welcome_alert <- function(){
    shinyalert(
        title = "Welcome to DDWizard",
        text = "<dl> This web application allows you to easily simulate and diagnose designs following the <a href = 'http://declaredesign.org'>DeclareDesign</a> framework. 
        <br/><br/>
        <dt>DESIGN TAB</dt>
        <br/>
        <dt>Design menu (top left)</dt>
        <dd>Load any of designer in the R package 'DesignLibrary'</dd>
        <dt>Left panel</dt>
        <dd>Set values of every argument in the chosen designer. Vector inputs need to be separated by commas.</dd>
        <dt>Central panel</dt>
        <dd>'Messages' display any warnings (e.g., when inputs are not valid).</dd>
        <dd>'Summary' displays a summary of the generated design.</dd>
        <dd>'Code output' displays R code to replicate the design.</dd>
        <dd>'Simulate data' allows you to draw, redraw, and download a single simulation of the data generated by the design.</dd>
        <br/><br/>
        <dt>INSPECT TAB</dt>
        <dd>Compare and diagnose your design by varying one or more parameters.</dd>
        </dl>
        ",
        closeOnEsc = TRUE,
        closeOnClickOutside = TRUE,
        html = TRUE,
        # type = "success",
        showConfirmButton = TRUE,
        showCancelButton = FALSE,
        confirmButtonText = "Get started",
        timer = 0,
        imageUrl = "",
        confirmButtonCol = "light-blue darken-3", 
        animation = TRUE
    )
}