app <- ShinyDriver$new("../", seed = 1)
app$snapshotInit("load_all_designs")

app$snapshot()
app$setInputs(`tab_design-import_design_library` = "binary_iv_designer")
app$setInputs(`tab_design-import_from_design_lib` = "click")
app$snapshot()
app$setInputs(`tab_design-import_design_library` = "block_cluster_two_arm_designer")
app$setInputs(`tab_design-import_from_design_lib` = "click")
app$snapshot()
app$setInputs(`tab_design-import_design_library` = "cluster_sampling_designer")
app$setInputs(`tab_design-import_from_design_lib` = "click")
app$snapshot()
app$setInputs(`tab_design-import_design_library` = "factorial_designer")
app$setInputs(`tab_design-import_from_design_lib` = "click")
app$snapshot()
app$setInputs(`tab_design-import_design_library` = "mediation_analysis_designer")
app$setInputs(`tab_design-import_from_design_lib` = "click")
app$snapshot()
app$setInputs(`tab_design-import_design_library` = "multi_arm_designer")
app$setInputs(`tab_design-import_from_design_lib` = "click")
app$snapshot()
app$setInputs(`tab_design-import_design_library` = "pretest_posttest_designer")
app$setInputs(`tab_design-import_from_design_lib` = "click")
app$snapshot()
app$setInputs(`tab_design-import_design_library` = "process_tracing_designer")
app$setInputs(`tab_design-import_from_design_lib` = "click")
app$snapshot()
app$setInputs(`tab_design-import_design_library` = "randomized_response_designer")
app$setInputs(`tab_design-import_from_design_lib` = "click")
app$snapshot()
app$setInputs(`tab_design-import_design_library` = "regression_discontinuity_designer")
app$setInputs(`tab_design-import_from_design_lib` = "click")
app$snapshot()
app$setInputs(`tab_design-import_design_library` = "spillover_designer")
app$setInputs(`tab_design-import_from_design_lib` = "click")
app$snapshot()
app$setInputs(`tab_design-import_design_library` = "two_arm_attrition_designer")
app$setInputs(`tab_design-import_from_design_lib` = "click")
app$snapshot()
app$setInputs(`tab_design-import_design_library` = "two_arm_covariate_designer")
app$setInputs(`tab_design-import_from_design_lib` = "click")
app$snapshot()
app$setInputs(`tab_design-import_design_library` = "two_arm_designer")
app$setInputs(`tab_design-import_from_design_lib` = "click")
app$snapshot()
app$setInputs(`tab_design-import_design_library` = "two_by_two_designer")
app$setInputs(`tab_design-import_from_design_lib` = "click")
app$snapshot()
